pipeline:
  name: "pg_to_snowflake_ingest"
  version: "1.0.0"
  domain: "data-platform"
  description: "Extract some data and load some data"

  schedule:
    type: "cron"
    expression: "0 3 * * *" #daily at 3 AM

  steps:
    - name: "extract-and-load"
      type: "ingestion"
      description: "Extract from Postgres, load into Snowflake"
      inputs:
        - name: "postgres-source"
          type: "postgres"
          host: "subscription-db.exampled.com"
          database: "subscriptions"
          table: "user_subscriptions"
      outputs:
        - name: "snowflake-dest"
          type: "snowflake"
          table_name: "analytics.user_subscriptions"

resources:
  compute_cluster: "data-platform-default-cluster"
